# Generated by Django 2.2 on 2022-02-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(default='', max_length=50, null=True)),
                ('card_number', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('cvc_number', models.IntegerField()),
            ],
        ),
    ]
