# Generated by Django 4.0.2 on 2022-02-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvc_number',
            field=models.IntegerField(max_length=4),
        ),
    ]
