# Generated by Django 4.0.2 on 2022-03-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_account_card_number_alter_account_cvc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='expiration_month',
            field=models.CharField(choices=[('1', '01 (Jan)'), ('2', '02 (Feb)'), ('3', '03 (Mar)'), ('4', '04 (Apr)'), ('5', '05 (May)'), ('6', '06 (Jun)'), ('7', '07 (Jul)'), ('8', '08 (Aug)'), ('9', '09 (Sep)'), ('10', '10 (Oct)'), ('11', '11 (Nov)'), ('12', '12 (Dec)')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='expiration_year',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033')], default='', max_length=50),
        ),
    ]
