# Generated by Django 4.0.2 on 2022-03-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_account_expiration_month_account_expiration_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
