# Generated by Django 4.0.2 on 2022-03-14 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0007_alter_account_expiration_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='expiration_month',
            field=models.IntegerField(choices=[(1, '01 (Jan)'), (2, '02 (Feb)'), (3, '03 (Mar)'), (4, '04 (Apr)'), (5, '05 (May)'), (6, '06 (Jun)'), (7, '07 (Jul)'), (8, '08 (Aug)'), (9, '09 (Sep)'), (10, '10 (Oct)'), (11, '11 (Nov)'), (12, '12 (Dec)')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='expiration_year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035')], null=True),
        ),
    ]
