# Generated by Django 2.2 on 2022-02-05 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Physics', 'Physics'), ('Math', 'Math'), ('English', 'English'), ('Engineering', 'Engineering')], default='', max_length=50)),
                ('course_number', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=50)),
                ('credit_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('is_instructor', models.BooleanField(default=False)),
                ('image_profile', models.CharField(default='', max_length=1000)),
                ('phone_number', models.CharField(default='', max_length=25)),
                ('addressLine1', models.CharField(default='', max_length=100)),
                ('addressLine2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('bio', models.TextField(default='', max_length=1000)),
                ('link1', models.CharField(default='', max_length=1000)),
                ('link2', models.CharField(default='', max_length=1000)),
                ('link3', models.CharField(default='', max_length=1000)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
