# Generated by Django 2.2 on 2022-01-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220126_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
