# Generated by Django 2.2 on 2022-01-30 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_submission'),
        ('users', '0004_auto_20220128_2105'),
    ]

    operations = [
    ]
