# Generated by Django 2.2 on 2022-02-06 06:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220205_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meeting_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(default='', max_length=1000, null=True, upload_to=''),
        ),
    ]
