# Generated by Django 2.2 on 2022-02-06 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220205_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='course',
            name='meeting_time_days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='', max_length=9),
        ),
    ]
