# Generated by Django 4.0.2 on 2022-02-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_usermessages_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
    ]
