# Generated by Django 4.0.2 on 2022-03-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usermessages_ignored'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tuition',
            field=models.IntegerField(default=0),
        ),
    ]
