# Generated by Django 2.2 on 2022-02-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(choices=[('Computer Science', 'COMPUTER SCIENCE'), ('Physics', 'PHYSICS'), ('Math', 'MATH'), ('English', 'ENGLISH'), ('Engineering', 'ENGINEERING')], default='Computer Science', max_length=6)),
                ('course_number', models.TextField(max_length=50)),
                ('course_name', models.CharField(max_length=100)),
                ('credit_hours', models.IntegerField(max_length=10)),
            ],
        ),
    ]
