# Generated by Django 2.2 on 2022-02-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='credit_hours',
            field=models.IntegerField(),
        ),
    ]
