# Generated by Django 2.2 on 2022-02-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220206_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(default='', null=True, upload_to='image_profile/'),
        ),
    ]
