# Generated by Django 2.2 on 2022-02-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220202_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='departments',
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.CharField(choices=[('computer science', 'Computer Science'), ('physics', 'Physics'), ('math', 'Math'), ('english', 'English'), ('engineering', 'Engineering')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='courses',
            name='credit_hours',
            field=models.IntegerField(max_length=9),
        ),
    ]
