# Generated by Django 2.2 on 2022-02-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220206_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='url',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
