# Generated by Django 2.2 on 2022-02-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220202_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='credit_hours',
            field=models.IntegerField(),
        ),
    ]
