# Generated by Django 2.2 on 2022-02-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userimage_url'),
        ('users', '0010_auto_20220206_0750'),
    ]

    operations = [
    ]
