# Generated by Django 3.1 on 2022-02-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220202_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Physics', 'Physics'), ('Math', 'Math'), ('English', 'English'), ('Engineering', 'Engineering')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(default='images/non/noimg.jpg', upload_to='images'),
        ),
    ]
