# Generated by Django 2.2 on 2022-02-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220202_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='addressLine1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='addressLine2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='link1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='link2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='link3',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Physics', 'Physics'), ('Math', 'Math'), ('English', 'English'), ('Engineering', 'Engineering')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(default='images/non/noimg.jpg', upload_to='images'),
        ),
    ]
