# Generated by Django 2.2 on 2022-02-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20220207_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meeting_time_days',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(default='', max_length=1000, upload_to=''),
        ),
    ]
