# Generated by Django 2.2 on 2022-02-08 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220207_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, null=True)),
                ('description', models.CharField(default='', max_length=1000, null=True)),
                ('due_date', models.DateTimeField(default=datetime.time, null=True)),
                ('file_type', models.CharField(max_length=10)),
                ('is_graded', models.BooleanField(default=False)),
                ('assignment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Submission')),
            ],
        ),
    ]
