# Generated by Django 3.1 on 2022-02-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220202_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_line1',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line2',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
