# Generated by Django 2.2 on 2022-02-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_assignment_submission'),
        ('users', '0013_auto_20220207_1432'),
    ]

    operations = [
    ]
