# Generated by Django 2.2 on 2022-02-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_assignment_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
