# Generated by Django 2.2 on 2022-02-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20220209_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(default='', max_length=50, null=True)),
                ('card_number', models.CharField(default='', max_length=20, null=True)),
                ('expire_date', models.DateField(default='', max_length=50, null=True)),
                ('cvc_number', models.CharField(default='', max_length=4, null=True)),
            ],
        ),
    ]
