# Generated by Django 2.2 on 2022-02-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220209_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv_number',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
