# Generated by Django 2.2 on 2022-02-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220209_0107'),
        ('users', '0022_auto_20220209_1032'),
    ]

    operations = [
    ]
