# Generated by Django 2.2 on 2022-02-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_merge_20220209_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
