# Generated by Django 2.2 on 2022-02-09 08:07

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Physics', 'Physics'), ('Math', 'Math'), ('English', 'English'), ('Engineering', 'Engineering')], default='', max_length=50)),
                ('course_number', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(2)])),
                ('course_name', models.CharField(max_length=50)),
                ('credit_hours', models.IntegerField()),
                ('meeting_time_days', models.CharField(default='', max_length=200)),
                ('start_time', models.TimeField(default=datetime.time)),
                ('end_time', models.TimeField(default=datetime.time)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, null=True)),
                ('description', models.CharField(default='', max_length=1000, null=True)),
                ('due_date', models.DateTimeField(default=datetime.time, null=True)),
                ('file_type', models.CharField(max_length=10)),
                ('is_graded', models.BooleanField(default=False)),
                ('assignment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Submission')),
            ],
        ),
    ]
