# Generated by Django 2.2 on 2022-02-11 22:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, null=True)),
                ('description', models.CharField(default='', max_length=1000, null=True)),
                ('due_date', models.DateTimeField(default=datetime.time, null=True)),
                ('max_points', models.IntegerField(default=0)),
                ('points_received', models.IntegerField(default=0, null=True)),
                ('file_type', models.CharField(max_length=10)),
                ('is_graded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Physics', 'Physics'), ('Math', 'Math'), ('English', 'English'), ('Engineering', 'Engineering')], default='', max_length=50)),
                ('course_number', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(2)])),
                ('course_name', models.CharField(max_length=50)),
                ('credit_hours', models.IntegerField()),
                ('meeting_time_days', models.CharField(default='', max_length=200)),
                ('start_time', models.TimeField(default=datetime.time)),
                ('end_time', models.TimeField(default=datetime.time)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
