# Generated by Django 2.2 on 2022-02-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points_received',
            field=models.IntegerField(default='', null=True),
        ),
    ]
