# Generated by Django 3.1 on 2022-02-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220210_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='points_received',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
