# Generated by Django 2.2 on 2022-02-11 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220210_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points_received',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
