# Generated by Django 2.2 on 2022-02-11 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20220210_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=datetime.date(2022, 2, 10), null=True),
        ),
    ]
