# Generated by Django 4.0.2 on 2022-02-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_assignment_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_id',
            new_name='submission_id',
        ),
    ]
