# Generated by Django 4.0.2 on 2022-02-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_courseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='file_type',
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('.file', 'File'), ('text', 'Text')], max_length=10, null=True),
        ),
    ]
