# Generated by Django 2.2 on 2022-02-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220210_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_course',
        ),
    ]
