# Generated by Django 4.0.2 on 2022-02-18 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0007_auto_20220216_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='submission_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='textbox',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
