# Generated by Django 4.0.2 on 2022-02-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, upload_to='file_submissions/% Y/% m/% d/'),
        ),
    ]
