# Generated by Django 4.0.2 on 2022-03-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_remove_assignment_is_graded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='max_points',
            field=models.IntegerField(default=0),
        ),
    ]
