# Generated by Django 4.0.2 on 2022-03-14 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_submission_max_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submit_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
