# Generated by Django 4.0.2 on 2022-03-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_submission_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='course',
        ),
    ]
