# Generated by Django 4.0.2 on 2022-03-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_submission_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='course',
        ),
    ]
